# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-05 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appnoticia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Helloworld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Nohelloworld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=100)),
            ],
        ),
    ]
